services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres
    command:
      - start
    networks:
      - keycloak-network
    environment:
      KC_HOSTNAME: $KC_HOSTNAME
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_PROXY: edge
      KEYCLOAK_ADMIN: $KEYCLOAK_ADMIN
      KEYCLOAK_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      # Database Configuration
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./themes:/opt/keycloak/themes/
      - ./providers:/opt/keycloak/providers/
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - keycloak
    networks:
      - keycloak-network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 1026:1025 # smtp server
      - 8026:8025 # web ui
    networks:
      - keycloak-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
